# Generated by Django 2.1.7 on 2019-05-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(blank=True, choices=[('01', 'ลากิจ'), ('02', 'ลาป่วย')], default='01', max_length=2, null=True),
        ),
    ]
