# Generated by Django 2.1.7 on 2019-05-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20190501_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('01', 'ลากิจ'), ('02', 'ลาป่วย')], default='01', max_length=2, null=True),
        ),
    ]
